export { default as MenuPage } from './MenuPage'
export { default as OrdersPage } from './OrdersPage'
export { default as TablesPage } from './TablesPage'
export { default as ReportsPage } from './ReportsPage'
export { default as UsersPage } from './UsersPage'